server:
  address: 0.0.0.0
  port: 8114
spring:
  cloud:
    nacos:
      discovery:
        namespace: cardflow
        group: dev
        password: ${NACOS_CARDFLOW_PASSWORD}
        username: cardflow
        server-addr: ${NACOS_CARDFLOW_ADDRESS}
      config:
        import-check:
          enabled: false
        # 当前服务启动后去nacos中读取配置文件的后缀
        file-extension: yml
        # 读取配置的nacos地址
        server-addr: ${NACOS_CARDFLOW_ADDRESS}
        # 读取配置的nacos的名空间
        namespace: cardflow-config
        password: ${NACOS_CARDFLOW_PASSWORD}
        username: cardflow
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:cardflow-share.yml
  application:
    name: cardflow-document

