dubbo:
  provider:
    retries: 0
    timeout: 5000
  application:
    logger: slf4j
    name: cardflow-card
  registry:
    address: nacos://${NACOS_CARDFLOW_ADDRESS}
    parameters:
      namespace: cardflow
      group: dev
      password: ${NACOS_CARDFLOW_PASSWORD}
      username: ${NACOS_CARDFLOW_USERNAME}
  protocol:
    # name: dubbo
    port: 50061

spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        # 当前服务启动后去nacos中读取配置文件的后缀
        file-extension: yml
        # 读取配置的nacos地址
        server-addr: ${NACOS_CARDFLOW_ADDRESS}
        # 读取配置的nacos的名空间
        namespace: cardflow-config
        password: ${NACOS_CARDFLOW_PASSWORD}
        username: ${NACOS_CARDFLOW_USERNAME}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      # - optional:nacos:SpringBootRabbitMQ.yml
  application:
    name: cardflow-card
logging:
  level:
    org.springframework.data.neo4j.cypher.deprecation: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb.client.model: DEBUG
