spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 7000
        response-timeout: 7000
        pool:
          type: fixed
          max-connections: 200
          max-idle-time: 20s
          max-life-time: 60s
      debug: true
    nacos:
      discovery:
        namespace: cardflow
        group: dev
        password: ${NACOS_CARDFLOW_PASSWORD}
        username: ${NACOS_CARDFLOW_USERNAME}
        server-addr: ${NACOS_CARDFLOW_ADDRESS}
      config:
        import-check:
          enabled: false
        # 当前服务启动后去nacos中读取配置文件的后缀
        file-extension: yml
        # 读取配置的nacos地址
        server-addr: ${NACOS_CARDFLOW_ADDRESS}
        # 读取配置的nacos的名空间
        namespace: cardflow-config
        password: ${NACOS_CARDFLOW_PASSWORD}
        username: ${NACOS_CARDFLOW_USERNAME}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  application:
    name: cardflow-gateway
